version: "3"

tasks:
  setup:
    cmds:
      - brew tap dbt-labs/dbt-cli
      - brew install dbt-cloud-cli
      - python -m pip install --progress-bar off -r requirements.txt
      - dbt deps
      - dbt seed
